services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    #ハードコーディングしないように.envから環境変数を使う
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend/app:/code/app
      - ./backend/uploads:/code/uploads
      - ./backend/data:/code/data
    
    env_file:
      - .env
      - ./backend/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/code
      - /code/node_modules #コンテナ内のライブラリを保護する
    env_file:
      - .env
      - ./frontend/.env